import enum

class RuleCategory(str, enum.Enum):
    AUTHENTICATION = "AUTHENTICATION"
    AUTHORIZATION = "AUTHORIZATION"
    INPUT_VALIDATION = "INPUT_VALIDATION"
    CONFIGURATION = "CONFIGURATION"
    CRYPTOGRAPHY = "CRYPTOGRAPHY"
    RATE_LIMITING = "RATE_LIMITING"
    INFORMATION_DISCLOSURE = "INFORMATION_DISCLOSURE"
    ANOMALY = "ANOMALY"
