FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scanner/ ./scanner
COPY backend/app ./app

CMD ["python", "-m", "scanner.engine"]
